#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

su glaesser -c 'tmux new -s "RRD Update Skripte" -d'
su glaesser -c 'tmux set remain-on-exit on'
su glaesser -c 'tmux new-window "/home/glaesser/update_database.sh"'
su glaesser -c 'tmux new_window "/home/glaesser/update_database_temperature_pressure.py"'

exit 0
